### ISSUE TITLE
clickOutsideToClose false is ignored on close action

### ISSUE THREAD

**Issue by eduardojmatos** [yapplabs/ember-modal-dialog#115] opened 2016-02-01 17:28 UTC
I'm extending the modal-dialog:

``` JavaScript
// app/components/action-modal.js

import ModalDialog from 'ember-modal-dialog/components/modal-dialog';

export default ModalDialog.extend({
  targetAttachment: 'center',
  renderInPlace: true,
  translucentOverlay: true,
  clickOutsideToClose: false,
});

```

Even passing `clickOutsideToClose` explicitly, the click on overlay triggers the `close` action.

In my component template...

``` Handlebars
<!-- app/templates/components/modal-alert.hbs -->

<div class="modal-dialog">

  {{#action-modal close="closeModal"}}

    <header class="ember-modal-head">
      <h1>{{attrs.title}}</h1>
      <button class="button button--close" type="button" {{action 'closeModal'}}>x</button>
    </header>

    <div class="ember-modal-body">
      {{yield}}
    </div>

  {{/action-modal}}

</div>

```

In my component file...

``` JavaScript
// app/components/modal-alert.js

import Ember from 'ember';

export default Ember.GlimmerComponent.extend({
  actions: {
    closeModal() {
      (this.attrs['close'] || Ember.K)();
    },
  },
});
```

Even with `clickOutsideToClose` false, the action `closeModal` on `app/components/modal-alert.js` is fired.

Is this a issue from add-on or it's my fault?

* * *

Infos:

**ember-cli version**: 1.13.13
**ember**: canary

**Comment by chrislopresto** [comment] 2016-02-06 01:10
Thanks for the writeup. After looking into things, it seems this is a duplicate of #106 

It turns out we accidentally broke `clickOutsideToClose` on `{{modal-dialog}}` with the https://github.com/yapplabs/ember-modal-dialog/releases/tag/v0.8.0 release. It does still work on `{{tether-dialog}}`, in case that helps.

I'm going to close this here in favor of #106. And to answer your question, it's not your fault. :smile:

**Closed by chrislopresto** 2016-02-06 01:10 UTC

**Comment by eduardojmatos** [comment] 2016-02-06 17:59
Tks @chrislopresto ! I'll try with `{{tether-dialog}}`. Tks! :+1:
