### ISSUE TITLE
Deprecation warning on Ember CLI master

### ISSUE THREAD

**Issue by constantm** [yapplabs/ember-modal-dialog#89] opened 2015-10-26 13:38 UTC
Using Ember CLI 1.13.8-master-ae5e72614e, I get the following deprecation warning:

`[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: ember-modal-dialog]`

**Comment by chrislopresto** [comment] 2015-10-26 14:20
@constantm What version of ember-modal-dialog are you using? I don't think we use `Funnel` anywhere.

**Comment by constantm** [comment] 2015-10-26 14:22
I did have a look through the code to see if I could provide a fix, and couldn't find any references. Version is 0.8.1. I wonder if it could be a bug in Ember CLI?

**Comment by chrislopresto** [comment] 2015-10-26 14:52
I just updated to Ember CLI 1.13.8 here https://github.com/yapplabs/ember-modal-dialog/pull/90 and still don't see the deprecation in the dummy app. We're guessing this is an issue on Ember CLI master. 

Thanks for bringing it to our attention. We'll bide our time for the time being. :hourglass:

**Comment by stefanpenner** [comment] 2015-10-26 15:26
> I wonder if it could be a bug in Ember CLI?

nope

**Comment by msalahz** [comment] 2015-11-12 12:25
I see this in the new ember-cli version :
```

**Comment by acorncom** [comment] 2015-11-12 17:55
I'm seeing this issue with ember-cli 1.13.11 as well (latest version as well , `"^0.8.2").  I'm not seeing any obvious use of the funnel stuff either though.  We might need to upgrade to a new ember-cli add-on?

**Comment by Dhaulagiri** [comment] 2015-11-13 13:12
Looks like [this was fixed in ember-cli](https://github.com/ember-cli/ember-cli/pull/5094) but I haven't confirmed

**Comment by vmalloc** [comment] 2015-11-15 13:38
+1 seeing this as well

**Comment by stefanpenner** [comment] 2015-11-15 17:25
yup, should be fixed on ember-cli. It had one remaining internal reference to `this.Funnel`

**Closed by stefanpenner** 2015-11-15 17:25 UTC
