### ISSUE TITLE
Opening modal fails in Ember 1.13.7+

### ISSUE THREAD

**Issue by elidupuis** [yapplabs/ember-modal-dialog#71] opened 2015-08-13 15:40 UTC
I was using `ember-modal-dialog` 0.7.7 and `ember` 1.13.6 and all was well. I just updated to Ember 1.13.8 and when I try to open a popover I get a `Uncaught TypeError: this.get(...).join is not a function` error from the [`modal-dialog` component](https://github.com/yapplabs/ember-modal-dialog/blob/master/addon/components/modal-dialog.js#L12).

I created a fresh project to test and can confirm that I see this error when using Ember 1.13.7 and 1.13.8.

![image](https://cloud.githubusercontent.com/assets/196410/9253793/0f6e6dfe-419d-11e5-9208-00a30b38780a.png)

![image](https://cloud.githubusercontent.com/assets/196410/9253818/3eef5bce-419d-11e5-9fe6-651e9837bed7.png)

**Comment by rondale-sc** [comment] 2015-08-14 14:56
This is also affecting me on:

```
cli: 1.13.8
ember 1.13.8
node: 0.12.2
npm: 2.13.4
os: darwin x64
```

**Comment by lukemelia** [comment] 2015-08-14 14:59
Thanks for the reports. We probably won't have time to track this down until the weekend. If anyone wants to dig in, please do.

**Comment by rondale-sc** [comment] 2015-08-14 15:06
@lukemelia I'm gonna try to dig in a bit.  :)

**Comment by rondale-sc** [comment] 2015-08-14 15:30
Changed `computedJoin` to:

```
const computedJoin = function(prop) {
  return computed(prop, function(){
    const p = this.get(prop)
    if (Ember.typeOf(p) === 'string') {
      return p;
    } else {
      return this.get(prop).join(' ');
    }
  });
};
```

And the modal popped, but isn't right.  The problem is that `this.get('containerClassNames')` is returning a string (in my case 'verify_modal') and computedJoin expects that to be an array.

Gonna keep looking.

**Comment by rondale-sc** [comment] 2015-08-14 16:10
Almost positive this has to do with `concatenatedProperties` http://emberjs.com/api/classes/Ember.Component.html#property_concatenatedProperties.  Still trying to get it to play nice.  

Seems as if:

`{{ x-foo bar="baz" }}` when `bar` is set to ["quux"]` in component

1.12: `bar` equals  `['baz', 'quux']
1.13 `bar equals 'baz'

Need to set `overlayClassNames` and `containerClassNames` in the `concatenatedProperties` array to ensure the old behavior.

**Comment by rwjblue** [comment] 2015-08-14 20:54
Should be fixed by https://github.com/emberjs/ember.js/pull/12104 which will end up in 1.13.9 and 2.0.1.

**Comment by elidupuis** [comment] 2015-08-14 21:00
:+1: Thanks guys!

**Comment by lukemelia** [comment] 2015-08-14 21:41
Thanks Jacksons! I'll keep this issue open until we can very in 1.13.9 and 2.0.1.

**Comment by rwjblue** [comment] 2015-08-23 01:38
@lukemelia - 1.13.9 and 2.0.1 have been released.

**Comment by danconnell** [comment] 2015-08-24 13:22
This doesn't appear to have been fixed in 1.13.9. I still get the same error.

**Comment by rwjblue** [comment] 2015-08-24 13:25
Ugh, looks like I screwed up the release (missed the important commit for this).  Sorry, I'll have to get a 1.13.10 out :(

**Comment by lukemelia** [comment] 2015-08-24 13:34
Thanks for checking @danconnell. We'll keep this open until next release.

**Comment by rwjblue** [comment] 2015-08-24 14:54
I just cherry-picked the fix into the `release-1-13` branch. This will be released as 1.13.10. It is likely going to be this weekend before I can release (to batch up a few more changes), but you can use it immediately in your applications via:

```
bower install --save ember#release-1-13
```

**Comment by elidupuis** [comment] 2015-08-24 15:23
Thanks!

**Comment by rwjblue** [comment] 2015-09-06 21:23
Time to try again.  Ember 1.13.10 / 2.0.2 / 2.1.0-beta.3 have been released.

**Comment by elidupuis** [comment] 2015-09-06 21:58
Just did a *really* quick test with *1.13.10* and my modals seem to work! :+1:

**Comment by danconnell** [comment] 2015-09-09 13:24
Works for me in 1.13.10

**Comment by lukemelia** [comment] 2015-09-09 15:30
Thanks all. Added a note to the README about 1.13.7-1.13.9 being problematic.

**Closed by lukemelia** 2015-09-09 15:30 UTC
Labels: bug
