### ISSUE TITLE
Simple install doesn't work

### ISSUE THREAD

**Issue by ptmoy2** [yapplabs/ember-modal-dialog#100] opened 2015-12-15 00:15 UTC
> ember new testModal
> cd testModal
> ember install ember-modal-dialog
> ember install ember-cli-sass
> ember serve

results in the error shown below

File not found: /app/styles/app.scss
in any of the following include paths:
  /home/pm/Projects/ember/testModal/tmp/sass_compiler-input_base_path-g9lZr7BL.tmp/0
Error: File not found: /app/styles/app.scss
in any of the following include paths:

**Comment by chrislopresto** [comment] 2015-12-15 15:10
@ptmoy2 By default, `ember new` will create `app.css`, and installing ember-cli-sass will _not_ change it to `app.scss`. Renaming `app.css` to `app.scss` should fix your problem.

Closing this issue here, as the problem is probably not related to ember-modal-dialog. Let me know if this does not solve things for you.

**Closed by chrislopresto** 2015-12-15 15:10 UTC

**Comment by ptmoy2** [comment] 2015-12-15 16:57
I renamed app.css to app.scss to get rid of the error on 'ember serve'.  But I still can get the basic example to work.  I tried:

     <h2 id="title">Welcome to Ember</h2>
     {{#modal-dialog}}
        Oh hai there!
     {{/modal-dialog}}
     {{outlet}}

No modal dialog was displayed.  Is there something else I need to do to set this up correctly?

**Comment by chrislopresto** [comment] 2015-12-15 17:29
Did you import the scss partials referenced in the README?

```scss
@import "ember-modal-dialog/ember-modal-structure";
@import "ember-modal-dialog/ember-modal-appearance";
```

**Comment by ptmoy2** [comment] 2015-12-15 17:38
My bad.  New to Ember-cli; still just plowing my way around.  Thanks for your help.

**Comment by chrislopresto** [comment] 2015-12-15 17:40
No worries. And welcome!
