### ISSUE TITLE
Scrollbar for large modals (or small browser window)

### ISSUE THREAD

**Issue by Keeo** [yapplabs/ember-modal-dialog#45] opened 2015-06-20 02:34 UTC
As title suggest, with large text or in window-centered modal there is no way how to click on buttons since they are out of screen. Could this be possible feature request?

**Comment by lukemelia** [comment] 2015-06-20 02:58
Agreed, this would be useful. Closing as a duplicate of #11

**Closed by lukemelia** 2015-06-20 02:58 UTC
