### ISSUE TITLE
error after updade to ember 2.8

### ISSUE THREAD

**Issue by albertonavarro087** [yapplabs/ember-modal-dialog#146] opened 2016-09-17 02:51 UTC
I'm getting this error after update to ember 2.8, I'm using the latest release of ember-modal-dialog 0.9.0

```
You cannot use `attributeBindings` on a tag-less component
```

Any ideas on this?

Thanks

**Comment by nightire** [comment] 2016-09-19 01:42
Actually this is totally right for a tag-less component, how would one provide "attributes" for a "tag-less" tag?

You can either create a child component to over-write `tagName` property or simply `{{modal-dialog tagName="div"}}` I guess, it should work.

**Comment by ghedamat** [comment] 2016-09-21 13:02
confirming this blocker as well

**Comment by benoror** [comment] 2017-04-04 22:13
Any workaround/update? We have a 2.7 -> 2.8 (and beyond) upgrade blocked by this very issue 😢

**Comment by lukemelia** [comment] 2017-04-05 03:41
@benoror It would be great to get a reproduction, preferably as a failing test.

FWIW, I'm using this project on multiple 2.12 apps with no issues. In addition CI is running on ember-2.8.0 successfully: See bottom of https://travis-ci.org/yapplabs/ember-modal-dialog/builds/218557677 for an example.

**Comment by lukemelia** [comment] 2017-05-16 04:25
Closing due to non-response. Feel free to comment/reopen.

**Closed by lukemelia** 2017-05-16 04:25 UTC
