### ISSUE TITLE
Extending breaks wormhole to modal-overlays on 2.1.x and 2.2.x

### ISSUE THREAD

**Issue by RyanHirsch** [yapplabs/ember-modal-dialog#97] opened 2015-11-17 17:34 UTC
Doing a simple extend of modal-dialog as shown below, does not wormhole to the correct `#modal-overlays` in Ember 2.1.x and 2.2.x but is fine on 1.13.x and 2.0.x.

```js
import ModalDialog from 'ember-modal-dialog/components/modal-dialog';

export default ModalDialog.extend({});
```

**Comment by jrowlingson** [comment] 2015-12-09 21:25
+1

**Comment by jrowlingson** [comment] 2016-01-05 15:54
@RyanHirsch Did you find a workaround?

**Comment by RyanHirsch** [comment] 2016-01-05 23:16
@jrowlingson no, we are holding on ember 2.0 for now.

**Comment by chrislopresto** [comment] 2016-01-08 05:57
@RyanHirsch Can you post a gist or some more details? I revved the ember-modal-dialog dummy apo to Ember 2.2.0 and everything is still behaving. Perhaps something else is afoot.

![modal-dialog-subclass-ember-2 2 0](https://cloud.githubusercontent.com/assets/93691/12191420/bd372038-b5a2-11e5-895f-af03c3009f5e.png)

**Comment by RyanHirsch** [comment] 2016-01-16 14:33
It doesn't seem to wormhole when you extend the modal-dialog. I made a quick repo here - https://github.com/RyanHirsch/ember-modal-demo/

**Comment by barryofguilder** [comment] 2016-01-18 16:36
I am extending the modal dialog and have the same issue after I updated my project from Ember 2.0.0 to 2.3.0.

**Comment by chrislopresto** [comment] 2016-01-20 16:59
@RyanHirsch Thanks, that will help a lot. I'm currently in a busy stretch on non-2.x apps, so I'm not sure when I'll dig in. 

I'd be happy to pair with you or anyone who might need this more urgently.

**Comment by beerlington** [comment] 2016-02-18 19:47
@chrislopresto just ran into this myself. Could I take you up on the offer to pair on it if you have time?

**Comment by chrislopresto** [comment] 2016-02-18 21:07
@RyanHirsch @beerlington Just took a look at https://github.com/RyanHirsch/ember-modal-demo/

The issue is that your custom component provides a template that clobbers the `modal-dialog` template. Deleting https://github.com/RyanHirsch/ember-modal-demo/blob/master/app/templates/components/custom-modal.hbs will fix everything up.

Let me know if this gets you unstuck and we'll close out this issue.

Thanks.

**Comment by beerlington** [comment] 2016-02-18 22:25
@chrislopresto yes that fixed it. Thanks!

**Comment by chrislopresto** [comment] 2016-02-18 23:08
Sure thing. Closing this.

**Closed by chrislopresto** 2016-02-18 23:08 UTC
